### ISSUE TITLE
Make asnyc

### ISSUE THREAD

**Issue by mammuth** [mammuth/ha-fritzbox-tools#1]

**Comment by AaronDavidSchneider** [comment]
Hey,
I have used your outdated component in the past and came up with a similar update of the component by using the switch component. My aproach has basically been the same, but I dropped the reconnect feature.
Anyway I just wanted to tell you, that I implemented my functions with async. Therefore if you want to double check, feel free to take a look on my implementation: https://github.com/AaronDavidSchneider/fritz_guestwifi

**Comment by mammuth** [comment]
Awesome, thanks for pinging back!

**Comment by mammuth** [comment]
Resolved by #27
