### ISSUE TITLE
Crash totally in Home Assistant 0.110.6

### ISSUE THREAD

**Issue by lrzdeveloper** [mammuth/ha-fritzbox-tools#101]
Hi, I've installed via HACS and put in the configuration.yaml the same configuration that you put in README, but once I rebooted, the system wasn't work correctly. If i login, the IP doesn't work. If I delete the folder in custom_configurations everything comes back ok. 
I see the log but I didn't find any errors.

**Comment by mammuth** [comment]
Without a log it's hard to tell what's going on.
 
Nevertheless, I suggest you try setting it up via the Integrations panel instead of the configuration.yaml.

**Comment by lrzdeveloper** [comment]
But in Integrations didn't see anything about this repo once I installed via HACS..

**Comment by ottelo9** [comment]
I've the same problems. I cannot find it on the Integration page.

**Comment by lrzdeveloper** [comment]
@mammuth How can we fix those problems? Both the crashing and searching in the Integration page...

**Comment by mammuth** [comment]
We should investigate why the integration is not showing up in the UI. The crashing is probably related to the yaml mode and we might even just get rid of it.

If you add another new integration via HACS, can it be added via the integration page of home assistant?

Just to make sure: you need to go to settings > integrations and hit the + button and search for this integration (it won't show up on the integration page by default).

**Comment by lrzdeveloper** [comment]
@mammuth Yes sure, I tested with another HACS integration like Garbage Collection and it shows it.
