### ISSUE TITLE
[feature request] Restart fritzbox from ha

### ISSUE THREAD

**Issue by FaserF** [mammuth/ha-fritzbox-tools#107]
Thanks for your custom component! Currently I am looking for an option to restart the fritbox from homeassistant.

Background story:
I am loosing my internet connection quite often from vodafone. The best fix always was to restart the fritzbox. I have already an automation which detects if the fritzbox looses the connection.

**Comment by AaronDavidSchneider** [comment]
This is already possible! Have a look at the readme :D

**Comment by FaserF** [comment]
Oh, I am sorry. I have read the readme.
Then I misunderstood the readme. maybe it can be updated.

For me a reconnect is no restart of the whole fritzbox. But thanks for clearing me out.

**Comment by AaronDavidSchneider** [comment]
I am sorry, you are right. This relates to a reconnect. I misunderstood you.
Are you sure that you really need to restart the fritzbox? Is a reconnect not sufficient?
I will reopen this issue.

**Comment by FaserF** [comment]
I will try it the next time with a reconnect. But from what I thought is, that if the fritzbox looses its connection to the ISP it does a reconnect trial automatically

**Comment by mammuth** [comment]
This got implemented by @AaronDavidSchneider, I'll try to create a release later.

**Comment by FaserF** [comment]
Wow, that was fast. Thanks for the great support and fast implementation 👍

**Comment by mammuth** [comment]
@AaronDavidSchneider is unstoppable sometimes! :rocket:

**Comment by mammuth** [comment]
Published to HACS as version 1.10.0
