### ISSUE TITLE
Better way of profile switches

### ISSUE THREAD

**Issue by AaronDavidSchneider** [mammuth/ha-fritzbox-tools#109]
I did a little research on the matter of profile switches and found an easier and stabler solution to our problem:
https://community.openhab.org/t/disable-internet-connection-of-specific-echo-device-on-fritz-box-via-script/91374

I quickly adapted the script to allow for a username. 

```bash
#!/bin/sh
challenge=$(curl -s "http://$1/login_sid.lua?username=$2" | grep -Po '(?<=<Challenge>).*?(?=</Challenge>)')
md5=$(echo -n ${challenge}"-"$3 | iconv -f ISO8859-1 -t UTF-16LE | md5sum -b | awk '{print substr($0,1,32)}') 
response="${challenge}-${md5}"
sid=$(curl -i -s -k -d "response=${response}&username=$2" "http://$1" | grep -Po -m 1 '(?<=sid=)[a-f\d]+' | tail -1)
curl -d "sid=${sid}&edit=$4&time=$5&budget=unlimited&apply=&page=kids_profileedit" "http://$1/data.lua" > /dev/null 2>&1
```

The idea is to save the code snippet to a script (e.g. `fritzboxprofile.sh`), make it executable (`chmod +x fritzboxprofile.sh`) and execute as:
`fritzboxprofile.sh [ip] [password] [profileid] unlimited`
or to disable internet access
`fritzboxprofile.sh [ip] [password] [profileid] never`

This will toggle the whole profile rather then specific devices. The big advantage is that a user could group devices in to groups in the fritzbox and then toggle the group whenever nescessary.

To do:
- [x] wrap this in an external python module and publish on pypi
(this way it can be downloaded by homeassistant)
- [x] automatically reveal profileid's
(I got the profile id from https://github.com/eifinger/fritz-switch-profiles with the commandline interface and --list-profiles).
- [x] a get command that reveals the current state

I don't have much time at the moment. So if anyone feels that this could be his/her contribution to fritzbox_tools, go for it!

The above script however already works quite well! Could be worth the effort.

Related issues: #105 #97 #90

**Comment by AaronDavidSchneider** [comment]
Example of how to read profileids:
Upon replacement of 
`curl -d "sid=${sid}&edit=$4&time=$5&budget=unlimited&apply=&page=kids_profileedit" "http://$1/data.lua" > /dev/null 2>&1`
to
`curl -d "sid=${sid}&page=kidPro" "http://$1/data.lua"`

gives a html response where one particular line is interesting:
```html
<table id="uiProfileList" class="zebra"><tr class="thead"><th class="name sortable">Name<span class="sort_no">&nbsp;</span></th><th class="sortable">Online-Zeit<span class="sort_no">&nbsp;</span></th><th class="sortable budget">Geteiltes Budget<span class="sort_no">&nbsp;</span></th><th class="sortable">Filter<span class="sort_no">&nbsp;</span></th><th class="sortable apps">Gesperrte Anwendungen<span class="sort_no">&nbsp;</span></th><th class="btncolumn"></th></tr><tr><td class="name" title="Standard" datalabel="Standard"><span>Standard</span></td><td datalabel="Online-Zeit">unbegrenzt</td><td datalabel="Geteiltes Budget"> — </td><td datalabel="Filter"> — </td><td datalabel="Gesperrte Anwendungen" class="apps"> — </td><td datalabel="" class="btncolumn"><button type="submit" name="edit" value="filtprof1" class="icon edit" title="Bearbeiten"></button><button onclick="return confirmDelete(&quot;Standard&quot;);" type="submit" name="delete" value="filtprof1" class="icon delete" title="Löschen" disabled></button></td></tr><tr><td class="name" title="Gast" datalabel="Gast"><span>Gast</span></td><td datalabel="Online-Zeit">unbegrenzt</td><td datalabel="Geteiltes Budget"> — </td><td datalabel="Filter">Blacklist</td><td datalabel="Gesperrte Anwendungen" class="apps"> — </td><td datalabel="" class="btncolumn"><button type="submit" name="edit" value="filtprof2" class="icon edit" title="Bearbeiten"></button><button onclick="return confirmDelete(&quot;Gast&quot;);" type="submit" name="delete" value="filtprof2" class="icon delete" title="Löschen" disabled></button></td></tr><tr><td class="name" title="Unbeschränkt" datalabel="Unbeschränkt"><span>Unbeschränkt</span></td><td datalabel="Online-Zeit">unbegrenzt</td><td datalabel="Geteiltes Budget"> — </td><td datalabel="Filter"> — </td><td datalabel="Gesperrte Anwendungen" class="apps"> — </td><td datalabel="" class="btncolumn"><button type="submit" name="edit" value="filtprof3" class="icon edit" title="Bearbeiten"></button><button onclick="return confirmDelete(&quot;Unbeschränkt&quot;);" type="submit" name="delete" value="filtprof3" class="icon delete" title="Löschen" disabled></button></td></tr><tr><td class="name" title="Gesperrt" datalabel="Gesperrt"><span>Gesperrt</span></td><td datalabel="Online-Zeit">keine</td><td datalabel="Geteiltes Budget">nein</td><td datalabel="Filter"> — </td><td datalabel="Gesperrte Anwendungen" class="apps"> — </td><td datalabel="" class="btncolumn"><button type="submit" name="edit" value="filtprof3378" class="icon edit" title="Bearbeiten"></button><button onclick="return confirmDelete(&quot;Gesperrt&quot;);" type="submit" name="delete" value="filtprof3378" class="icon delete" title="Löschen"></button></td></tr></table>
```

If this response is filtered (postprocessed by python) all relevant information like disabled/enabled (although in german: "keine" instead of never) or profile_id for a given profile name are exposed.

Therefore this command might be particulary useful for chalange 2 and 3.

**Comment by mammuth** [comment]
> although in german: "keine" instead of never

Hm, that might be an issue right? Because then it will probably also be reported in other languages which makes it harder to identify the state (unless we know the term in all supported languages).

**Comment by AaronDavidSchneider** [comment]
> > although in german: "keine" instead of never
> 
> Hm, that might be an issue right? Because then it will probably also be reported in other languages which makes it harder to identify the state (unless we know the term in all supported languages).

I will try to find a language independent response. This should be somehow possible. I will take some free time this evening and make a first draft.

**Comment by AaronDavidSchneider** [comment]
I got most of it working...
https://github.com/AaronDavidSchneider/fritzprofiles

However: I have too little (no) knowledge of xpath. Therefore I can not figure out how to extract the info needed for the status. Do you know xpath @mammuth? More information in the readme and the code.

If I get the extraction of the information for the status working, I can make a PR to replace the existing module by my (lighter) module. 
What do you think?

**Comment by mammuth** [comment]
> However: I have too little (no) knowledge of xpath.

Me neither sadly. :smirk:

> If I get the extraction of the information for the status working, I can make a PR to replace the existing module by my (lighter) module.
What do you think?

If it's expected to work at least as good as the original library this obviously makes sense.

I could imagine that some issues arise over time when users with different router models / OS versions test it, which means additional maintenance burden compared to the original library.

**Comment by AaronDavidSchneider** [comment]
That is true. The problem with this is that you need html scraping (same problem for the original module).
However, the only difference between my code and the original code is that my code is lighter and written to work with homeassistant and that I understand where possible errors may come from and issues can be fixed instead of redirecting to some misterious module.

**Comment by mammuth** [comment]
Makes sense. 

Are you using xpath for sending queries or only for parsing HTML? If it's for parsing, you could use `beautifulsoup`.

**Comment by AaronDavidSchneider** [comment]
Yes only for parsing. Queries are only done by requests.
Xpath It’s really painful. But I got it working. The module can now set and get the status of a profile. That’s everything we need for homeassistant.

**Comment by mammuth** [comment]
Closed by https://github.com/mammuth/ha-fritzbox-tools/pull/110

Releasted as pre-release version `1.11.0`
