### ISSUE TITLE
can't ignore

### ISSUE THREAD

**Issue by sagitt** [mammuth/ha-fritzbox-tools#122]
new version for multiple routers can't permit to ignore other routers. I have 2 extender and i can't ignore configuration for it.

**Comment by AaronDavidSchneider** [comment]
Thanks for testing! Please explain what you mean by ignore configuration?

**Comment by sagitt** [comment]
> Thanks for testing! Please explain what you mean by ignore configuration?

as official home assistant integration, now i have an alert for discovered integration every time i restart home assistant i have it in to integration. Home Assistant permit to ignore auto-discovered integration. see first 4 integration. are ignored.


![Schermata 2020-10-26 alle 13 27 45](https://user-images.githubusercontent.com/169086/97172265-1715d100-178f-11eb-9d3c-248ed614ad46.png)

**Comment by AaronDavidSchneider** [comment]
Thats interesting indeed! I must have overlooked that. I will try to find a solution and come back to you.

**Comment by sagitt** [comment]
> Thats interesting indeed! I must have overlooked that. I will try to find a solution and come back to you.

thanks, that's is really annoying :D

**Comment by AaronDavidSchneider** [comment]
Please test @sagitt. Tell me if you need help :D

**Comment by sagitt** [comment]
> Please test @sagitt. Tell me if you need help :D

i not have any update in my hacs

**Comment by AaronDavidSchneider** [comment]
You only need to take the files from https://github.com/AaronDavidSchneider/ha-fritzbox-tools/tree/config_flow_fix and replace the files in `custom_components` of your home assistant device.

Thanks!

**Comment by sagitt** [comment]
> You only need to take the files from https://github.com/AaronDavidSchneider/ha-fritzbox-tools/tree/config_flow_fix and replace the files in `custom_components` of your home assistant device.
> 
> Thanks!

works

**Comment by AaronDavidSchneider** [comment]
ok thanks for reporting and testing!

**Comment by sagitt** [comment]
> ok thanks for reporting and testing!

when you release it?

**Comment by AaronDavidSchneider** [comment]
> > ok thanks for reporting and testing!
> 
> when you release it?

I minimalized the PR, could you please try again and confirm that it still works? Thanks!
I think as soon as @mammuth tested it. But there is really no hurry since this is not really an urgent fix :D

**Comment by sagitt** [comment]
> > > ok thanks for reporting and testing!
> > 
> > 
> > when you release it?
> 
> I minimalized the PR, could you please try again and confirm that it still works? Thanks!
> I think as soon as @mammuth tested it. But there is really no hurry since this is not really an urgent fix :D

works. for me is urgent fix :D

**Comment by AaronDavidSchneider** [comment]
Then just keep the files from the PR and you are good to go. Stay tuned at PR #123
