### ISSUE TITLE
Fritzbox Mesh: Determining on which AP device is logged on?

### ISSUE THREAD

**Issue by AdmiralRaccoon** [mammuth/ha-fritzbox-tools#128]
Hi,
I have a 7590, a 7490 and a 1750E Repeater in a mesh in my house, every device on one floor.
 Would it be possible for fritzbox-tools to gather the information, which Wifi Device is on which AP? 

(Eg, the MAC from entity device_tracker.android1234 is logged on to the 1750E, so I know it´s in the basement).
Agreed, it´s not very useful for fast automations like turning lights on, as the Mesh (for now) is rather slow in roaming devices, but I thinks this is getting better in every FritzOS release)

**Comment by chemelli74** [comment]
This custom integration is now deprecated because is fully merged into HomeAssistant core.

I would suggest you open a feature request on [HomeAssistant Community forum](https://community.home-assistant.io/)

Simone
