### ISSUE TITLE
Enable Callblock for DECT Phones

### ISSUE THREAD

**Issue by WolfsWelpe** [mammuth/ha-fritzbox-tools#132]
Hello,

Is it possible with ha-fritzbox-tools to enable/disable Callblock for specific DECT Phones ?
So you can do something like a do not disturb button in Home Assistant to disable all ringing ?

**Comment by snickers2k** [comment]
+1
i would love to enable/disable dnd for phones by arming/disarming the house-alarm

**Comment by WolfsWelpe** [comment]
Heyho,

Just a question is there any plan to integrate that sooner or later?
Just curious no pressure ^^

**Comment by mammuth** [comment]
This custom integration is soon fully ported into Home Assistant Core.

New feature might be added directly to core, then. 

Personally, I'm not motivated to implement it, because I have no DECT devices. But PRs are always welcomed.

**Comment by WolfsWelpe** [comment]
Wow thanks for the quick reply.
Where do I have to submit the PR then? Is this still enough?

**Comment by mammuth** [comment]
This is the ported HA core integration: https://github.com/home-assistant/core/tree/dev/homeassistant/components/fritz

However, I recommend you wait until the following PR is merged, because it will integrate the first switches into the integration: https://github.com/home-assistant/core/pull/51610

**Comment by chemelli74** [comment]
This custom integration is now deprecated because is fully merged into HomeAssistant core.

I would suggest you configure the new integration and retest your issue; if still present then open a issue on HomeAssistant Core repository.

Simone
