### ISSUE TITLE
Issue with profiles setup 

### ISSUE THREAD

**Issue by erdemw** [mammuth/ha-fritzbox-tools#133]
Setup does not accept any access profile name. It allways says, wrong format or name. I was not able to find any format description in the documentation. I tried different profile names that were properly configured and working in Fritz Box and also payed attention to lower/upper case.  

What do I have to do?

**Comment by AaronDavidSchneider** [comment]
Here is an example of my setup:
![Screenshot 2020-12-22 at 14 37 36](https://user-images.githubusercontent.com/7556347/102894347-3d8c7b80-4463-11eb-9233-45c24c691f42.png)

To control the profiles I need to put:
![Screenshot 2020-12-22 at 14 38 57](https://user-images.githubusercontent.com/7556347/102894465-6dd41a00-4463-11eb-8efa-199b619b9e66.png)

I hope this example helps :D

**Comment by erdemw** [comment]
Thank you so much for your quick reply! My Fritzbox setup looks quite similar (see screenshot 1). However, in the meantime I deleted and reinstalled the integration. This time the system accepted the access profile (maybe a typo in my credentials?), but it ist greyed out and I cannot toggle it (screenshot 2). 
![Screenshot 2](https://user-images.githubusercontent.com/76076049/102899698-a0821080-446b-11eb-9de4-9baf577edee2.png)
![Screenshot 1](https://user-images.githubusercontent.com/76076049/102899706-a11aa700-446b-11eb-9458-7b508b99ee54.png)

**Comment by AaronDavidSchneider** [comment]
I can see the confusion now. The current version of [fritzprofiles](https://github.com/AaronDavidSchneider/fritzprofiles) can only toggle the online time between `never` and `unlimited` (in German: `keine` and `unbegrenzt`).
You will therefore need to replace the calendar of the FritzBox by some automations in home assistant.
This has already been mentioned here: #121

**Comment by erdemw** [comment]
That solved the issue. Thanks alot!! 
However, I would appreciate it if - in one of the next updates - there would be an option to keep Fritzbox as the leading system when it comes to time budget since it can detect whether the internet access within an access profile group of devices is actually in use or not and I am not aware of a method to capture that figure in order to automate within HA. For me it is not only a matter of time scope (i.e. 8.00 - 20.00) but also of online duration time in total (i.e. 1h a day).

**Comment by AaronDavidSchneider** [comment]
Thanks for your feedback! You are totally right about the time budget aspect.
I think it might be quite complicated to include the `limited` option in fritzprofiles. Whenever you toggle from `limited` to `never` or `unlimited` you would again manually need to set all options for that profile.
I fear that this can only be done inside the FritzBox.

**Comment by chemelli74** [comment]
This custom integration is now deprecated because is fully merged into HomeAssistant core.

I would suggest you configure the new integration and retest your issue.
After reading the [documentation](https://www.home-assistant.io/integrations/fritz), if still present then open a issue on HomeAssistant Core repository.

Simone
