### ISSUE TITLE
Uninstalling FritzBox_Tools

### ISSUE THREAD

**Issue by laccio85** [mammuth/ha-fritzbox-tools#134]
I have completely uninstalled the component via HACS.
I always get this error every time I start HA:

ERROR (MainThread) [homeassistant.setup] Setup failed for fritzbox_tools: Integration not found.

and the subsequent notification in HA:

Invalid config
The following integrations and platforms could not be set up:

fritzbox_tools
Please check your config and logs.

How can I permanently delete this component and its notification?

**Comment by mammuth** [comment]
Please make sure to uninstall via the integration pane if you installed it over this way and check your `configuration.yaml`.
You'll also need to restart home assistant.

**Comment by laccio85** [comment]
Mammunt forgive me but I've been making several attempts for at least 3 days now, the notification and the error is still there.
I can't figure out which way is it possible to delete the component completely?
here is the log extract:

Logger: homeassistant.setup
Source: setup.py:138
First occurred: 22 dicembre 2020, 23:03:35 (1 occurrences)
Last logged: 22 dicembre 2020, 23:03:35

Setup failed for fritzbox_tools: Integration not found.

**Comment by mammuth** [comment]
As stated in the previous issue: did you make sure that your `configuration.yaml` doesn't include `fritzbox_tools:`?

**Comment by mammuth** [comment]
If this is not the cause, maybe HACS somehow loads it.

**Comment by laccio85** [comment]
In my configuration.yaml there is no longer any entry "fritzbox_tools:".

**Comment by laccio85** [comment]
> If this is not the cause, maybe HACS somehow auto-loads it.

If this is the problem, how can I remove the autoload from HACS???
