### ISSUE TITLE
Uninstalling FritzBox_Tools #2

### ISSUE THREAD

**Issue by laccio85** [mammuth/ha-fritzbox-tools#135]
Mammunt forgive me, related request issue #134, but I've been making several attempts for at least 3 days now, the notification and the error is still there.
I can't figure out which way is it possible to delete the component completely?
here is the log extract:

Logger: homeassistant.setup
Source: setup.py:138
First occurred: 22 dicembre 2020, 23:03:35 (1 occurrences)
Last logged: 22 dicembre 2020, 23:03:35

Setup failed for fritzbox_tools: Integration not found.

**Comment by mammuth** [comment]
No need to keep opening more issues for the same topic
