### ISSUE TITLE
"This AVM FRITZ!Box is already configured."

### ISSUE THREAD

**Issue by Senbei123** [mammuth/ha-fritzbox-tools#137]
I installed the Fritz Box Tools a couple of days ago but newer integrate it.

Then I guess I delete manual the folder and today I install the tools again with HACS.

In the integration page I enter my IP-Adress and User/Password and then get the following issue:
"This AVM FRITZ!Box is already configured."

But unfortunately I don't find any integration entry, also no entries are listed..
Also in configuration.yaml nothing is stored.

Any suggestion how to solve this?

**Comment by AaronDavidSchneider** [comment]
This might sound stupid, but did you restart HA during the process.

This should in principle work:
1. remove all Fritzbox tools entries (configuration.yaml and integration pane)
2. restart HA
3. delete Fritzbox Tools from hacs 
4. restart Ha
5. install Fritzbox Tools from hacs
6. restart ha
7. re-add Fritzbox Tools

Usually steps 3-6 are unnecessary.
When configured correctly step 2 should also be unnecessary (if there are no leftovers in configuration.yaml)

If this does not work for you, head over to the configuration pane in HA. I think you can manually remove old entities there (should normally not be nescessary).

Good luck!

**Comment by Senbei123** [comment]
Hi,
thanks for the support - I tried all steps without success..

Then I do some research on the ".storage" folder and find in those two files a few lines inlcuding a reference to the fritz Tools.
   hacs.repositories
   core.config_entries

I make a backup of the files, delete the not necessary lines and restart home assistant.
Then I install fritz tools with HACS again + restart home assistant.
With the restart the notification popus up, that the system finds a new integraton - The fritz tools.
Setting up username and passwort works like a charm. :)

THANKS!

**Comment by mammuth** [comment]
Thanks for commenting the final solution!

Then apparently something during the uninstall went wrong. The question is whether this is an issue on our side, hacs or maybe even core.

**Comment by Senbei123** [comment]
I guess it was me, because I delete the folder in the custom_component folder manually.. ;)
