### ISSUE TITLE
Safe to Use?

### ISSUE THREAD

**Issue by WolfsWelpe** [mammuth/ha-fritzbox-tools#142]
Hello,

Is this custom integration safe to use due to new Informations:
https://www.home-assistant.io/blog/2021/01/22/security-disclosure/

**Comment by mammuth** [comment]
Well the core team didn't reach out nor did they share concrete about the details about the issue so we could verify that it doesn't affect this integration.

> Home Assistant released Home Assistant Core 2021.1.3 with extra protection to stop directory traversal attacks before reaching the vulnerable code. This prevents the abuse of all found vulnerabilities.

Combined with this quote my answer for you is `yes`
