### ISSUE TITLE
Fritz Repeater 2400 - always re-descovers this device after restart of core

### ISSUE THREAD

**Issue by pichlerralf** [mammuth/ha-fritzbox-tools#145]
Hello,
the Integration always rediscovers my Fritz Repeater 2400 after restart of Core, Supervisor or host. 
I have several other Fritz products running (Repeater 1750E, Dect Repeater and 7490), these are running fine. 
Seems like it does not store the credentials of this specific device. 

Thanks in advance for fixing.

**Comment by mammuth** [comment]
Sounds like a misbehavior, indeed. 
In the meantime you could disable discovery for the integration if this annoys you (the HA docs should have information about this)

**Comment by pichlerralf** [comment]
Thanks fo the fast note. 
as i do not need to restart this often its not annoying. 
just wanted to file this for future fixing which surely helps other users too. 
nevertheless thanks for this great Integration!

**Comment by pichlerralf** [comment]
Any chance this will get fixed in the next versions?

**Comment by mammuth** [comment]
> Any chance this will get fixed in the next versions?

I'm not actively looking into this and if it's not significantly affecting others, chances are a bit low that anyone will pick it up I'd assume.

**Comment by Ergerbolt** [comment]
For me the same. After every restart, the add on rediscovers and i have to set up the config again.

**Comment by chemelli74** [comment]
This custom integration is now deprecated because is fully merged into HomeAssistant core.

I would suggest you configure the new integration and retest your issue.
After reading the [documentation](https://www.home-assistant.io/integrations/fritz), if still present then open a issue on HomeAssistant Core repository.

Simone
