### ISSUE TITLE
Guest-Wifi switch entity doesn't get created

### ISSUE THREAD

**Issue by Fabenissimo** [mammuth/ha-fritzbox-tools#15]
Hi!

on appx. every 2nd reboot of HA my guestwifi switch doesn't get created, the logs show the following:

```
fritzbox_tools: Error on device update!
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity_platform.py", line 292, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 441, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/fritzbox_tools/switch.py", line 162, in update
    from fritzconnection.fritzconnection import AuthorizationError
ImportError: cannot import name 'AuthorizationError' from 'fritzconnection.fritzconnection' (/srv/homeassistant/lib/python3.7/site-packages/fritzconnection/fritzconnection.py)
```

**Comment by mammuth** [comment]
Looks like a strange error. Maybe we should see whether the upstream library should be updated and double check our import statements.

**Comment by AaronDavidSchneider** [comment]
We should try using fritzconnection version 0.8.4.
@Fabenissimo: what other fritz related integrations do you use with home assistant? Maybe one of them uses old fritzconnection library (which doesn’t include authorizationerror) and gets sometimes loaded before ha_fritzbox_tools

**Comment by Fabenissimo** [comment]
In addition to this component I'm using the fritzbox component [https://www.home-assistant.io/components/fritzbox/](url) and the "old" firtzboxguestwifi custom component from @mammuth.

I've now commented out the old custom component (which I should have done in the first place) and done five subsequent restarts of HA. Every time the entitiy got created so I would consider the issue solved.

Thanks for the quick help!

**Comment by AaronDavidSchneider** [comment]
The old guestwifi component uses an outdated fritzconnection library.
I am glad I could help you :D

**Comment by mammuth** [comment]
> I've now commented out the old custom component (which I should have done in the first place) and done five subsequent restarts of HA.

Yeah, then the package structure changed between the used versions in this new component and the old one. And depending on which component got load first the new or old package got installed and linked (not quite sure how HA handles conflicting dependency versions though).
