### ISSUE TITLE
Cannot see the users who logged in the fritzbox

### ISSUE THREAD

**Issue by manuelo1983** [mammuth/ha-fritzbox-tools#157]
Hello,
I only can see if the wlan is on or off also for the guest network, but I cannot see if there is anybody connected an who.
I want to send a notification, if anybode login to the guest wlan, but at the moment there is no sensor for it.

Best Regards
Manuel

**Comment by chemelli74** [comment]
I'm going to add `device_tracker` platform to this great integration.

Later on we'll see if there is the info on which WIFI device is connected.

Simone

**Comment by manuelo1983** [comment]
That sounds very good!!!!!!

**Comment by manuelo1983** [comment]
Have you tried something with the device tracker? Regards Manuel

**Comment by TheZoker** [comment]
@manuelo1983 The `device_tracker` is actually now integrated directly inside HA core: https://github.com/home-assistant/core/pull/48287
and available since today with HA `2021.5.0`:
https://www.home-assistant.io/blog/2021/05/05/release-20215/#integrations-now-available-to-set-up-from-the-ui

**Comment by chemelli74** [comment]
This custom integration is now deprecated because is fully merged into HomeAssistant core.

I would suggest you open a feature request on [HomeAssistant Community forum](https://community.home-assistant.io/)

Simone
