### ISSUE TITLE
Device profile switcher

### ISSUE THREAD

**Issue by jacobgibbs** [mammuth/ha-fritzbox-tools#16]
I found this project which I thought may be of use to you: https://github.com/flopp/fritz-switch-profiles

I know being able to switch profiles was discussed in #6 and I don't know Python (or even own a fritzbox at the moment!) but thought it'd be worth posting this here as I discovered it when researching

**Comment by mammuth** [comment]
Thanks for the hint. 

Interesting. In #6 it sounded like the protocol would not support it, so it might be interesting to take a look how the mentioned package does allow setting of the profiles.

**Comment by mammuth** [comment]
I'll close this issue in favor of the other one (which contains more meaningful history of conversation)
