### ISSUE TITLE
Possibility to read out Logfile?

### ISSUE THREAD

**Issue by Zuendapp** [mammuth/ha-fritzbox-tools#160]
Hi Folks,

is it possible to read out the log file and write it to a database?

Thank you very much!

BR

**Comment by mammuth** [comment]
Hi, so you want to read the logfile of your router and store it "somewhere" in home assistant? (Eg the database that is defined via the `recorder:`)

This integration is using the library `fritzconnection` if the library supports accessing logfiles, it might be possible.

**Comment by Zuendapp** [comment]
Hi,

yes, I want to check the daily disconnect, etc. 
Can you implement this?

Thank you very much!

Bar

**Comment by chemelli74** [comment]
This custom integration is now deprecated because is fully merged into HomeAssistant core.

Daily disconnects can be seen soon using the WAN uptime sensor: [Fix wan/device uptime and add state_class to counters for Fritz](https://github.com/home-assistant/core/pull/52574)

Simone
