### ISSUE TITLE
2021.5.4 update has broken Fritzbox-Tools

### ISSUE THREAD

**Issue by Darren-Hill** [mammuth/ha-fritzbox-tools#166]
Just updated, and now getting multiple log errors and the addon is basically broken.

Binary sensor for external IP address, and all switches for wifi access and profiles are now unavailable.

> Logger: homeassistant.components.binary_sensor
> Source: custom_components/fritzbox_tools/common.py:181
> Integration: Binary sensor (documentation, issues)
> First occurred: 9:56:35 AM (1 occurrences)
> Last logged: 9:56:35 AM
> 
> Error while setting up fritzbox_tools platform for binary_sensor
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 231, in _async_setup_platform
>     await asyncio.shield(task)
>   File "/config/custom_components/fritzbox_tools/binary_sensor.py", line 36, in async_setup_entry
>     async_add_entities([FritzBoxConnectivitySensor(fritzbox_tools)], True)
>   File "/config/custom_components/fritzbox_tools/binary_sensor.py", line 52, in __init__
>     f"fritzbox_{self.fritzbox_tools.fritzbox_model}_connectivity"
>   File "/config/custom_components/fritzbox_tools/common.py", line 181, in fritzbox_model
>     return self._device_info["model"].replace("FRITZ!Box ", "")
> AttributeError: 'FritzBoxTools' object has no attribute '_device_info'

> Logger: homeassistant
> Source: custom_components/fritzbox_tools/switch.py:127
> Integration: FRITZ!Box Tools (documentation)
> First occurred: 9:56:39 AM (1 occurrences)
> Last logged: 9:56:39 AM
> 
> Error doing job: Future exception was never retrieved
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
>     result = self.fn(*self.args, **self.kwargs)
>   File "/config/custom_components/fritzbox_tools/switch.py", line 127, in _create_profile_switches
>     if len(fritzbox_tools.profile_switch) > 0:
> AttributeError: 'FritzBoxTools' object has no attribute 'profile_switch'

> Logger: homeassistant
> Source: custom_components/fritzbox_tools/common.py:181
> Integration: FRITZ!Box Tools (documentation)
> First occurred: 9:56:39 AM (1 occurrences)
> Last logged: 9:56:39 AM
> 
> Error doing job: Future exception was never retrieved
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
>     result = self.fn(*self.args, **self.kwargs)
>   File "/config/custom_components/fritzbox_tools/switch.py", line 152, in _create_wifi_switches
>     [FritzBoxWifiSwitch(fritzbox_tools, net, networks[net])],
>   File "/config/custom_components/fritzbox_tools/switch.py", line 619, in __init__
>     f"fritzbox_{self._fritzbox_tools.fritzbox_model}_{id}"
>   File "/config/custom_components/fritzbox_tools/common.py", line 181, in fritzbox_model
>     return self._device_info["model"].replace("FRITZ!Box ", "")
> AttributeError: 'FritzBoxTools' object has no attribute '_device_info'

**Comment by mammuth** [comment]
Did you try removing + re-adding the custom integration?

**Comment by Darren-Hill** [comment]
Rolled back to 2021.5.3 and then updated again to 5.4 ready to try your suggestion, and this time it seems to be working fine?

So I guess something screwed up with the original update from 5.3 to 5.4. 

Anyway all good again, can close this one off...
