### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by genex89** [mammuth/ha-fritzbox-tools#167]
when I try to install the component via HACKS, the installation never ends and the ram is occupied until the Raspberry becomes unreachable.
I tried several times but in the end I always have to delete the component folder and restart to unlock.

HA Core installation on rpi 3b +

**Comment by mammuth** [comment]
Most of the Features of this custom integration have been migrated into the latest HA core Version, so I'd recommend using the one from core and not installing this one via HACS.

**Comment by genex89** [comment]
I understand, I was interested because this integration also allows you to turn on and off the guest wifi, while the official one does not

**Comment by mammuth** [comment]
@chemelli74 might have information on when the guest wifi will also land in core.

You also didn't attach any logs to your initial comment - if you want to continue trying the custom integration, I'd recommend checking the logs.

**Comment by chemelli74** [comment]
[Add switch platform info to Fritz](https://github.com/home-assistant/home-assistant.io/pull/18131) :-)

Simone

**Comment by chemelli74** [comment]
Done, all merged. Now just wait for 2021.7.0 :-)

Simone
