### ISSUE TITLE
Access profiles reset after turn on/off

### ISSUE THREAD

**Issue by Huber1** [mammuth/ha-fritzbox-tools#168]

**Comment by Huber1** [comment]
Sorry forgot the description:
If you switch an access profile to on or off, it resets the configuration for that profile.
In my case, it disables the blacklist check and the guest wifi check.
The "gesperrte Netzwerkanwendungen" Tab is not affected

**Comment by AaronDavidSchneider** [comment]
That is true. But that's also the case if you do so in the Fritzbox UI.

**Comment by Huber1** [comment]
If I set the time to never for a profile in the edit window it doesn't affect the other settings. They stay activated

**Comment by AaronDavidSchneider** [comment]
Could you please open this issue at the upstream library?
https://github.com/AaronDavidSchneider/fritzprofiles 

I will have a look into it when I have some more time!

Thanks already for reporting the issue!

**Comment by Huber1** [comment]
Sure. Thanks for investing time in that plugin!

**Comment by Huber1** [comment]
Sorry that I didn't respond earlier, but I didn't have time because of some tests at school.
I see you fixed the issue in fritzprofiles. Would it be possible to update the dependencies in this repo to use the fixed version in HomeAssistant?

**Comment by AaronDavidSchneider** [comment]
Hi, that was the idea:

https://github.com/home-assistant/core/pull/52618

However, we realised that fritzprofiles is not suitable to be used in home assistant (it's using webscraping).

We are now working on new ways to Switch the internet access of devices. 

PS: this custom integration is now outdated and succeeded by the homeassistant core Fritz integration.
