### ISSUE TITLE
entity_ids are created with name instead of unique_id

### ISSUE THREAD

**Issue by AaronDavidSchneider** [mammuth/ha-fritzbox-tools#18]
I just discovered that my entities are not created with entity_ids matching the pattern in the property unique_id. Instead home assistant translates the names to entity_ids. 
For example:
`unique_id = 'fritzbox_guestwifi'`
`name = 'FRITZ!Box Guest Wifi'`
is instead:
`entity_id: fritz_box_guest_wifi`

**Comment by mammuth** [comment]
Yeah, I noticed that as well...
I'd be great to have a consistent naming scheme across all entities that are exposed by this custom integration.

I'd prefer `[type].fritzbox_[...]`.

**Comment by AaronDavidSchneider** [comment]
I have gone through the source code of some home assistant components and found out how entity_ids are named. Its actually not so difficult.

**Comment by AaronDavidSchneider** [comment]
@mammuth: Now that #17 is merged. You should have a look at the entity_id names and also change the README for the changed names.

**Comment by mammuth** [comment]
The readme looks up to date to me and on my test setup all entities have the `fritzbox_`-prefix (don't have the port switches on this machine, but in the code it looks correct as well)
