### ISSUE TITLE
Replace old-fashioned formats with f-strings

### ISSUE THREAD

**Issue by mammuth** [mammuth/ha-fritzbox-tools#32]
I think we use some '{}'.format()` or even `'%s'` string formats.

f-strings are available since Python 3.6 which is also the minimum required version by Home Assistant.

So we can easily use f-strings everywhere (if suitable).

(good first issue since it allows you to browse through the code a bit)

**Comment by AaronDavidSchneider** [comment]
I think, I actually included this fix already in my pull request #28
