### ISSUE TITLE
CI flake8 tests not running as expected

### ISSUE THREAD

**Issue by mammuth** [mammuth/ha-fritzbox-tools#33]
https://github.com/mammuth/ha-fritzbox-tools/pull/28

This pull request had some issues flake8 should have complained about, but didn't.

**Comment by AaronDavidSchneider** [comment]
I think, I don't really grasp the error. I am not familiar with flake8 anyway. Can you tell me how to fix it?

**Comment by mammuth** [comment]
I recently [added travis-ci](https://github.com/mammuth/ha-fritzbox-tools/blob/master/.travis.yml) to check commits and pull requests for their code style, but it didn't report issues on your PR.

Probably, I already found the fix, I'll push it into master.

If you want to see the errors locally, you can run the following command in the root of the project:
`git diff master...[your_config_validation_branch_name] | flake8 --diff .`

However I'm a bit surprised due to the high number of errors when running it for your pull request. Maybe your recent merge of `master` introduced a syntax error?

**Comment by mammuth** [comment]
Probably fixed in https://github.com/mammuth/ha-fritzbox-tools/commit/3011a42a0e525c2239698eb2b04fdd7a0a52e9d5

But let's see how it behaves in future PRs

**Comment by chemelli74** [comment]
This custom integration is now deprecated because is fully merged into HomeAssistant core.
