### ISSUE TITLE
Add "connected since" to connectivity sensor

### ISSUE THREAD

**Issue by mammuth** [mammuth/ha-fritzbox-tools#35]
In the web UI the router shows for how long it has been connected to the ISP. 

We're setting information like the IP addresses and uptime as attributes on our connectivity sensor.
I'm not sure whether "connected for" is available through the API, but if so, we could add it to the sensors attributes.

Great first issue (tinker with fritzconnection and see whether the value is exposed, then integrate it with the sensor)

**Comment by AaronDavidSchneider** [comment]
Closed by latest release.
