### ISSUE TITLE
Can't change port forwarding status

### ISSUE THREAD

**Issue by sagitt** [mammuth/ha-fritzbox-tools#43]
i'm not able to switch port forwarding.... but it see correctly the status from router

**Comment by mammuth** [comment]
Just to be clear: It's only possible to toggle the port forward for the device running home assistant.

Are there any messages from this component in your home assistant log?

**Comment by sagitt** [comment]
i know, but not work. last hass, last version of plugin, last fritzos on 7590

**Comment by mammuth** [comment]
Did you enable the settings from the following screenshot?
![](https://user-images.githubusercontent.com/3121306/68996105-e5fe0280-0895-11ea-8b0d-1a4487ee6838.png)

If not, we definitely need logs to help you further.

**Comment by sagitt** [comment]
yes, for example guest wifi works very well.

**Comment by AaronDavidSchneider** [comment]
do you have "selbständige Portfreigabe" enabled for the IP address of your homeassistant device?

**Comment by AaronDavidSchneider** [comment]
Please paste any related error in your homeassistant log (see `Developer Tools` - `Logs`)

**Comment by sagitt** [comment]
> do you have "selbständige Portfreigabe" enabled for the IP address of your homeassistant device?

In english?

**Comment by AaronDavidSchneider** [comment]
Permit independent port sharing for this device

**Comment by sagitt** [comment]
In the device i have this.

I setter some ports manually

![E56A64FE-6553-4E10-B663-281223FB5278](https://user-images.githubusercontent.com/169086/71127188-de11e500-21ea-11ea-9b69-41fcb2a5b10d.png)

**Comment by mammuth** [comment]
You need to check the second checkbox. 

And we should probably add a screenshot for that to the Readme, so it's easier to understand.

**Comment by FrancYescO** [comment]
Having the same issue, also seems the integrations does not detect right all my port forwardings:

This is what i have in hassio
<img width="786" alt="immagine" src="https://user-images.githubusercontent.com/4574593/74482480-e1f17900-4eb4-11ea-82c0-c6a91c9bf1ad.png">
these my port forwardings on fritz:
<img width="1093" alt="immagine" src="https://user-images.githubusercontent.com/4574593/74482557-0cdbcd00-4eb5-11ea-933a-b2f57a44c7a7.png">

This is the errorlog when trying to switch a _(name desynced as shown)_ entity:
```Home Assistant cannot call the wished service on the FRITZ!Box.

Traceback (most recent call last):
  File "/config/custom_components/fritzbox_tools/switch.py", line 268, in _async_handle_port_switch_on_off
    self.connection_type, "AddPortMapping", **self.port_mapping
  File "/usr/local/lib/python3.7/site-packages/fritzconnection/core/fritzconnection.py", line 207, in call_action
    return self.soaper.execute(service, action_name, arguments)
  File "/usr/local/lib/python3.7/site-packages/fritzconnection/core/soaper.py", line 170, in execute
    return handle_response(response)
  File "/usr/local/lib/python3.7/site-packages/fritzconnection/core/soaper.py", line 153, in handle_response
    raise_fritzconnection_error(response)
  File "/usr/local/lib/python3.7/site-packages/fritzconnection/core/soaper.py", line 82, in raise_fritzconnection_error
    raise exception(message)
fritzconnection.core.exceptions.FritzArgumentValueError: UPnPError: 
errorCode: 600
errorDescription: Argument Value Invalid
```

**Comment by sagitt** [comment]
anyway, i not need this feature. i think an option to disable it is the best thing.

**Comment by chemelli74** [comment]
This custom integration is now deprecated because is fully merged into HomeAssistant core.

I would suggest you configure the new integration and retest your issue.
After reading the [documentation](https://www.home-assistant.io/integrations/fritz), if still present then open a issue on HomeAssistant Core repository.

Simone
