### ISSUE TITLE
Switch for calldeflection

### ISSUE THREAD

**Issue by Krocko** [mammuth/ha-fritzbox-tools#45]
Hello. 
Thank you for working on this integration. 
Would it be possible for you to add a switch, to turn on/off the calldeflection?
See here:
https://gist.github.com/fake666/75c035c74b7be448dd9b3d1316ea6cfe

**Comment by mammuth** [comment]
Thanks for your suggestion.

Your linked component uses the same library (`fritzconnection`) as we do, so it should be pretty easy to integrate it here. 

Pull requests welcome :blush:

**Comment by mammuth** [comment]
Note the following comment from the gist:

> removing and adding calldeflections while homeassistant is running will break this ;-)

This should probably be avoided if possible.

**Comment by Krocko** [comment]
Thank you very much for your fast response. 
Do you mean, you can do the integration?
I would be happy to help on this with testing. 
But I have really no clue from coding.

**Comment by mammuth** [comment]
> Do you mean, you can do the integration?

It should be easily doable from a technical point of view. 
I'm not quite sure whether we should add it here, or rather wait until we merged this integration into HA core... (related #29)

**Comment by Krocko** [comment]
I think, you should add it here.
So we can test it, before merging in the HA core.

**Comment by Krocko** [comment]
Hi @mammuth. Can you please integrate this calldeflection feature from @AaronDavidSchneider?

**Comment by mammuth** [comment]
Yes, it's on my list to review and integrate it 😊

**Comment by Krocko** [comment]
Would be really cool!
Thank you both.

**Comment by mammuth** [comment]
PR is merged.
