### ISSUE TITLE
List of all Network Devices

### ISSUE THREAD

**Issue by Syndlex** [mammuth/ha-fritzbox-tools#48]
I would like to monitor which devices are in my network.

Could you pls add a functionality to get all List of all devices that are currently in the Network.

I will try implementing this myself but i don't have a lot of time at the moment.

**Comment by AaronDavidSchneider** [comment]
Have a look at the fritz integration in homeassistant core:
https://www.home-assistant.io/integrations/fritz/

**Comment by mammuth** [comment]
You should probably be able to accomplish your use case with the mentioned device tracker in Home Assistant core. If not, feel free to explain it, maybe it makes sense to expose a sensor with a list or something like that.

**Comment by Syndlex** [comment]
This has more to do with device tracking.
The Problem is that the device tracker doesn't gives Information about IPs.

**Comment by Krocko** [comment]
I would like this idea too. 
The Fritzbox device tracker don‘t show up and mac.

**Comment by AaronDavidSchneider** [comment]
I checked the fritzconnection library. I think it should be fairly easy to add this feature in a pull request to the fritz integration.
I will try this.

**Comment by AaronDavidSchneider** [comment]
Issue can be closed @mammuth.
Pull request in fritz core integration has been merged.

**Comment by mammuth** [comment]
Yes, that's the much more correct approach in my opinion :+1:
