### ISSUE TITLE
Profile device list is not updated once devices is set in config

### ISSUE THREAD

**Issue by tekgator** [mammuth/ha-fritzbox-tools#49]
Initially I didn't work with the device switch in the config. Since I got alot devices I turned on this feature to only have the devices available I like to change the profile for e.g.

`  
devices: # Optional. Needed if you want to control the profiles of your network devices.
    - "Helens-iPhone"
    - "Aarons-MacBook-Air"
    - "..."
`

Now new devices have been added to the network and I have extended the devices switch in the config. Still the device _switch.fritzbox_profile_<new devicename>_ is not showing up in HA.
I then removed the devices switch completely in the config.
Still **no** new and also the old once in the network are added as a _switch.fritzbox_profile_<devicename>_.

**Comment by tekgator** [comment]
I guess it is related to the change in 1.5? I deleted the integration and trying to reintegrate it. Now I'm asked for username, password and device list, etc. in the integration. Is the config now obsolete?

![image](https://user-images.githubusercontent.com/11077551/71641361-f11cbe80-2c9a-11ea-95b3-979075e31065.png)

**Comment by AaronDavidSchneider** [comment]
Both ways are possible now.
You can either add the integration using configuration.yaml or using the integrations panel.

**Comment by tekgator** [comment]
Hello @AaronDavidSchneider that's what I did and it fixed the problem.
