### ISSUE TITLE
Use local IP address from HA for port forward switch

### ISSUE THREAD

**Issue by AaronDavidSchneider** [mammuth/ha-fritzbox-tools#52]
Homeassistant has a utility function to determine the local IP address (see https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/util/__init__.py#L95) which is also used in the HomeKit Integration. If we would use this function we wouldn’t need the configuration option for homeassistant_ip

**Comment by mammuth** [comment]
Ah, that's great. 👍 

According to the implementation, we should check whether the result is `"127.0.0.1"` because that gets returned in case of an error. In this case, we should not set up the switches.

**Comment by AaronDavidSchneider** [comment]
Yeah thats sounds good!
