### ISSUE TITLE
Profile change set up problem

### ISSUE THREAD

**Issue by deluxestyle** [mammuth/ha-fritzbox-tools#55]
Hi,

I would like to setup this component with the possibility to switch the profile for one device.
during the start following error occurs:

```
Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/fritzbox_tools/switch.py", line 58, in _create_profile_switches
    devices = fritzbox_tools.profile_switch.get_devices()
AttributeError: 'FritzBoxTools' object has no attribute 'profile_switch'
```

My setup:
Hass.io 0.104.2 in docker on a rasperrby pi 3+

my config:
```
fritzbox_tools:
  host: fritz.box
  username: !secret fritz_user
  password: !secret fritz_password
  devices:
    - my_device
```

**Comment by mammuth** [comment]
Thanks for the report. I didn't take a look in detail, but the issue might be rooted in the upgraded version of `fritzconnection` in home assistant 0.104.

**Comment by AaronDavidSchneider** [comment]
@deluxestyle:
please try to specify `profile_on` and `profile_off` in your yaml and report if this works for you.

**Comment by deluxestyle** [comment]
@AaronDavidSchneider same issue
@mammuth it is the first time that I'm using your component

**Comment by AaronDavidSchneider** [comment]
Can you try to add the component using the integrations panel? @deluxestyle

**Comment by deluxestyle** [comment]
@AaronDavidSchneider yes, this is working.

**Comment by AaronDavidSchneider** [comment]
Could you try again with the yaml configuration by applying my PR @deluxestyle?

If you need help: head over to my pull request and replace your __init__.py file by my changed one.

**Comment by mammuth** [comment]
I just released your PR as 1.5.2. 
@deluxestyle If you're installing it via HACS, you can manually refresh the repository and update to 1.5.2 and try reconfiguring the component via configuration.yaml

**Comment by AaronDavidSchneider** [comment]
Hey @mammuth:
I just added another fix to the branch. I was obviously a little bit to late :D 
However, this one should also be necessary ...

**Comment by mammuth** [comment]
Well, nobody could expect me being that fast, since it has been rather the opposite in the past 🙈😁 
Let's open a PR for the branch again and publish it after merging?

**Comment by AaronDavidSchneider** [comment]
no problem :D just did that @mammuth

**Comment by deluxestyle** [comment]
ihr seid echt schnell :-) ich warte noch kurz

**Comment by mammuth** [comment]
> ihr seid echt schnell :-) ich warte noch kurz

published, please update & reconfigure the component in order to verify the fix by @AaronDavidSchneider 😊

**Comment by deluxestyle** [comment]
I can confirm it is working
thank you
