### ISSUE TITLE
Add device profiles

### ISSUE THREAD

**Issue by mammuth** [mammuth/ha-fritzbox-tools#6]
```
Is it also possible to create a switch for a device “profile”?
I have a internet profil for my kids phone that turns the wifi off in the night on weekdays - but want to leave it on if the weekday is a bank holiday (will be checked from a google calender) and other automations
```

https://community.home-assistant.io/t/control-fritz-box-guest-wifi-and-trigger-internet-reconnects/137344/2?u=mammuth

ToDo:
- Evaluate whether / how that's possible with https://github.com/kbr/fritzconnection

**Comment by AaronDavidSchneider** [comment]
there is no such thing unfortunately. Fritzconnection only supports getting host information, but not setting them. There is also no way to communicate the "kindersicherungs" (or device profile) using TR064.
See e.g. in fritzhosts.py:
```
def get_hosts_info(self):
        """
        Returns a list of dicts with information about the known hosts.
        The dict-keys are: 'ip', 'name', 'mac', 'status'
        """
        result = []
        for index in range(self.host_numbers):
            host = self.get_generic_host_entry(index)
            result.append({
                'ip': host['NewIPAddress'],
                'name': host['NewHostName'],
                'mac': host['NewMACAddress'],
                'status': host['NewActive']})
        return result
```
So basically ip, mac, name and status (I think speed is also possible for wifi devices) is all you can get.

However setting the device profile from home assistant would be a really cool thing...

**Comment by mammuth** [comment]
> However setting the device profile from home assistant would be a really cool thing...

Indeed, that'd be pretty nice!

Thanks for the insights, when the protocol isn't even capable of doing this, I'll mark this one as wontfix.

**Comment by mammuth** [comment]
Might be interesting to take a look at https://github.com/flopp/fritz-switch-profiles as pointed out by @jacobgobbs in #16

**Comment by AaronDavidSchneider** [comment]
That is a really cool library! I don't really fully understand how they implement it. But they use some kind of xml requests at the fritzbox. I experimented a little with it and am going to create a pull request to include this into ha-fritzbox-tools.

**Comment by mammuth** [comment]
Sounds awesome!
Although I'm not actively using profiles myself, I could imagine a lot of people would find this really helpful!

**Comment by jacobgibbs** [comment]
Glad you found it useful! This will probably convince me to get a fritzbox...

**Comment by mammuth** [comment]
Done by #17 and #26
