### ISSUE TITLE
Option for disabling port forwarding

### ISSUE THREAD

**Issue by sagitt** [mammuth/ha-fritzbox-tools#61]
Before last update, without local ip i can disable port forwarding
now i'm forced to have this items

maybe an option to disable port forwarding items?

thanks

**Comment by mammuth** [comment]
What's your reasoning why you want to get rid of them? 
Isn't it enough to just not add them to your UI?

**Comment by sagitt** [comment]
> What's your reasoning why you want to get rid of them?
> Isn't it enough to just not add them to your UI?

Because i need to create rules for exclude items from cloud services and homekit, update rules every time that i need to add port fowarding items and i have no items hided, so i need to add new rules to “other items” tab when i have all not used items

And for now, port forwarding not work, show correct status and details but can’t enable or disable it from hass.

**Comment by sagitt** [comment]
use_port: True  # Optional, default True: if False no port switches will be exposed

new version have this option, configuring it with use_port: false or use_port: False won't work. Hass won't restart giving an error.

**Comment by mammuth** [comment]
Please try using the integration UI.

**Comment by AaronDavidSchneider** [comment]
Also: what is the error?

**Comment by sagitt** [comment]
> 
> 
> Please try using the integration UI.

I prefer yaml mode, anyway after reinstalling the new release no error, but my ports switch are again visible

this is my configuration

fritzbox_tools:
  host: !secret fritzbox_host
  username: !secret fritzbox_username
  password: !secret fritzbox_password
  use_port: false

**Comment by chemelli74** [comment]
This custom integration is now deprecated because is fully merged into HomeAssistant core.

I would suggest you configure the new integration and retest your issue; if still present then open a issue on HomeAssistant Core repository.

Simone
