### ISSUE TITLE
Sensor for connected Guest Devices

### ISSUE THREAD

**Issue by AdmiralRaccoon** [mammuth/ha-fritzbox-tools#64]
Hello,
I would be grateful for a sensor that lists the amount (And maybe the device name?) of connected guest wifi devices. (Within the Fritzbox, all guest devices have a suitcase symbol before the device name)
I would like to setup notifactions if there are any guest devices online when they are not supposed to be online.

Thanks you,
Philipp

**Comment by mammuth** [comment]
I didn't look into the data we get about connected devices, but I could imagine that it's possible.

**Comment by AaronDavidSchneider** [comment]
I just looked into the data of connected devices. Here is an example of the response:

Guestwifi:
```py
{'NewIPAddress': '192.168.179.45',
 'NewAddressSource': 'DHCP',
 'NewLeaseTimeRemaining': 21598,
 'NewInterfaceType': '802.11',
 'NewActive': True,
 'NewHostName': 'Aarons-iPhone'}
```

Normal wifi:
```py
{'NewIPAddress': '192.168.178.48',
 'NewAddressSource': 'DHCP',
 'NewLeaseTimeRemaining': 0,
 'NewInterfaceType': '802.11',
 'NewActive': True,
 'NewHostName': 'Aarons-iPhone'}
```

You can see that there is a difference in the Adresse range (normal wifi uses 192.168.178. ..., while guest wifi uses 179). This might be different for your fritzbox anyway.

I think if you want to monitor the devices in your guestnetwork, you would need to filter devices in this specific ip range.

This is the command I used to get the information:
```py
from fritzconnection import FritzConnection
c = FritzConnection(address = "192.168.178.1", user="pi", password="blub")
c.call_action("Hosts1","GetSpecificHostEntry",NewMACAddress="blub")
```

**Comment by chemelli74** [comment]
This custom integration is now deprecated because is fully merged into HomeAssistant core.

I would suggest you open a feature request on [HomeAssistant Community forum](https://community.home-assistant.io/)

Simone
