### ISSUE TITLE
0.105 not work

### ISSUE THREAD

**Issue by sagitt** [mammuth/ha-fritzbox-tools#65]
after the 0.105 update, plugin won't work.

**Comment by mammuth** [comment]
Yes, update will follow soon.

**Comment by sagitt** [comment]
well :)

anyway i see this:

Dettagli registro (ERROR)
Sun Feb 09 2020 10:17:16 GMT+0100 (Ora standard dell’Europa centrale)
Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 109, in async_init
    result = await self._async_handle_step(flow, flow.init_step, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 172, in _async_handle_step
    result: Dict = await getattr(flow, method)(user_input)
  File "/config/custom_components/fritzbox_tools/config_flow.py", line 170, in async_step_import
    CONF_PROFILE_ON: user_input.get(CONF_PROFILE_ON, DEFAULT_PROFILE_ON),
NameError: name 'user_input' is not defined

**Comment by AaronDavidSchneider** [comment]
> well :)
> 
> anyway i see this:
> 
> Dettagli registro (ERROR)
> Sun Feb 09 2020 10:17:16 GMT+0100 (Ora standard dell’Europa centrale)
> Error doing job: Task exception was never retrieved
> Traceback (most recent call last):
> File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 109, in async_init
> result = await self._async_handle_step(flow, flow.init_step, data)
> File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 172, in _async_handle_step
> result: Dict = await getattr(flow, method)(user_input)
> File "/config/custom_components/fritzbox_tools/config_flow.py", line 170, in async_step_import
> CONF_PROFILE_ON: user_input.get(CONF_PROFILE_ON, DEFAULT_PROFILE_ON),
> NameError: name 'user_input' is not defined

See issue #63. will be fixed in the next release.

**Comment by mammuth** [comment]
Closed by #59 

Release 1.7.0 is available via HACS.

**Comment by sagitt** [comment]
Good, but wifi 2,4 ghz and 5ghz are now in 1 toggle?

![964C358C-A090-4ACD-8620-D65048C0FBA0](https://user-images.githubusercontent.com/169086/74101607-cd6f5280-4b3b-11ea-81b5-dde13bb56f81.jpeg)

**Comment by mammuth** [comment]
Yep, seems to be a new bug. See #66
