### ISSUE TITLE
Guest wifi switch toggles main wifi 5ghz

### ISSUE THREAD

**Issue by mammuth** [mammuth/ha-fritzbox-tools#66]
On version 1.7.0 of this integration, the guest wifi switch toggles the main wifi 5ghz instead of the guest wifi.
For 5ghz no entity is created at all.

So apparently the identification/mapping of available networks is wrong. 

Introduced by #59 and #54 
Maybe related #60

**Comment by Krocko** [comment]
The same for me.

**Comment by AaronDavidSchneider** [comment]
should be closed by PR #67

**Comment by mammuth** [comment]
Version 1.7.1 of this integration provides a fix for this.
