### ISSUE TITLE
Integration has no visible title when adding it via UI

### ISSUE THREAD

**Issue by mammuth** [mammuth/ha-fritzbox-tools#71]
When searching for the integration, the row is empty / has no visible title.
Also, the next steps don't have any labels etc.

![Screenshot 2020-02-14 at 15 33 10](https://user-images.githubusercontent.com/3121306/74540109-80c2b780-4f3f-11ea-9f10-3580f9e67704.png)

![Screenshot 2020-02-14 at 15 33 15](https://user-images.githubusercontent.com/3121306/74540114-81f3e480-4f3f-11ea-8bde-40b7d98ccfc4.png)

![Screenshot 2020-02-14 at 15 36 30](https://user-images.githubusercontent.com/3121306/74540298-d008e800-4f3f-11ea-8cbe-5ebf0466b335.png)

I disabled my theme. 

@AaronDavidSchneider I first noticed this after upgrading to 1.8.0 / after the changes to the feature flags in the config flow. 🤔 But I don't see what's causing it.

**Comment by AaronDavidSchneider** [comment]
Must be a mismatch of the translation files. I will have a look into it soon

**Comment by mammuth** [comment]
Ah sure, sounds obvious.

**Comment by AaronDavidSchneider** [comment]
I just checked it @mammuth. It should work without any problems (it works in my test and production setup). Which language do you use? I think it only works with german and english (as of en.json and de.json in .translations).
Could you check your local files?
Is there a related log message?

**Comment by mammuth** [comment]
I checked both, en and de. Since I didn't find any issues I reinstalled it a second time which somehow magically resolved the issue.
