### ISSUE TITLE
Two or more fritz!box in one integration...Possible?

### ISSUE THREAD

**Issue by giustanca** [mammuth/ha-fritzbox-tools#72]
Is there any way to integrate two fritz!box available in the same mesh network?
There's a way to have the status of two different devices in the same integration?

**Comment by AaronDavidSchneider** [comment]
This is currently not possible. This would only affect the sensor and not the switches, since the mesh master is the one that decides if the WiFi should be turned on/off, etc.
What feature would you like to monitor in your homeassistant setup?

**Comment by giustanca** [comment]
I would need the binary-sensor connection status of the second router and the ability to turn on/off the guest wifi of the second router

**Comment by jankatins** [comment]
>  is the one that decides if the WiFi should be turned on/off,

Not every network contains a mesh network, e.g. I can imagine a case where I connect a second box (or a repeater) via LAN and let it open a new wifi.

**Comment by AaronDavidSchneider** [comment]
I thought about this lately. I don't see a why we couldn't implement it. However, it seems that this would conflict the current naming of entityids...

Imagine we have a setup including a Fritzbox 7530 (mesh master or modem) and a Fritzbox 4020 (mesh client or second box / repeater). My suggestion would be to have two entries (for each FB one integration).

This would be my suggestion for the naming :

| Current        | New           | 
| ------------- |:-------------:| 
|`service.reconnect`                                | `service.reconnect_7530`,  `service.reconnect_4020`|
`service.reboot`                                        | `service.reboot_7530`,  `service.reboot_4020`|
`switch.fritzbox_wifi`                               | `switch.fritzbox_7530_wifi`, `switch.fritzbox_4020_wifi` |
`switch.fritzbox_wifi_5ghz`                    | same scheme... with fritzbox_name_Y |
`binary_sensor.fritzbox_connectivity`  | same scheme... with fritzbox_name_Y |
`switch.fritzbox_portforward_X`.         | same scheme... with fritzbox_name_Y |
`switch.fritzbox_profile_X`.                   | same scheme... with fritzbox_name_Y |
`switch.fritzbox_deflection_X`               | same scheme... with fritzbox_name_Y |

What do you think @jankatins, @giustanca, @mammuth?
How would we deal with the case where two fritzboxes of the same type are used in one network (even though that seems unlikely?!)

**Comment by jankatins** [comment]
My suggestion would be to use ip adresses or mac adresses: at my parents we have one fritzbox and two repeater of the same make. so using the model would not work in that case.

**Comment by AaronDavidSchneider** [comment]
> My suggestion would be to use ip adresses or mac adresses: at my parents we have one fritzbox and two repeater of the same make. so using the model would not work in that case.

both seems pretty ugly... Could you try the current PR and report the naming in case of multiple fritzboxes?

**Comment by supergageto** [comment]
Hi,
I tried already 5 times to unsubscribe from this thread but still receiving it.
I would like not getting emails anymore.

Thanks

**Comment by giustanca** [comment]
And so? We don't write anymore so we don't bother you?

**Comment by AaronDavidSchneider** [comment]
This discussion can be held in PR #119.

**Comment by jankatins** [comment]
Sorry, my HA is here and I've no way to run it in my parents network :-(

The fritzbox upnp integration makes the devices show up with the hostname as part of the entity id. That would be a third way to make it unique.
