### ISSUE TITLE
Avoid state "jiggling" after changing the guest wifi switch

### ISSUE THREAD

**Issue by mammuth** [mammuth/ha-fritzbox-tools#8]
Since the switch now gets its state from the FRITZ!Box, the button can jiggle to the previous state after you hit it, because the router needs some time to turn guest wifi on.

Is there a common best practice how to tackle this?

**Comment by AaronDavidSchneider** [comment]
There is a should_poll property, that could be set to false for some seconds.
See: https://developers.home-assistant.io/docs/en/entity_index.html
I am trying to implement this now. I'll come back to you soon.

**Comment by AaronDavidSchneider** [comment]
Hey Max,
I have fixed the jiggling (see my new commit). The reason for the jiggling was a fairly stupid:
We didn't update the state variable when we toggled the switch. It toggled back to its original state therefore.
To give the fritzbox the time to toggle the wifi, I adapted your idea to use a timestamp.

**Comment by mammuth** [comment]
What a stupid mistake :see_no_evil: 
Do you want to open a pull request or should I manually insert the code?

**Comment by AaronDavidSchneider** [comment]
I can open a pull request

**Comment by AaronDavidSchneider** [comment]
I am not familiar with pull requests, but I tried to publish a branch with the new commit. I am not allowed to publish the branch.
```
ERROR: Permission to mammuth/ha-fritzbox-tools.git denied to AaronDavidSchneider.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
