### ISSUE TITLE
Deflection toggle - arguments order

### ISSUE THREAD

**Issue by PetePete** [mammuth/ha-fritzbox-tools#80]
according to https://forum.fhem.de/index.php?topic=92247.0 there is a bug in the firmware which requires a specific order of arguments to toggle call deflections.

In switch.py, line 410
This would be correct and is working for me:
`self.fritzbox_tools.connection.call_action(
                "X_AVM-DE_OnTel:1","SetDeflectionEnable", NewDeflectionId=self.id, NewEnable=new_state
            )`

**Comment by AaronDavidSchneider** [comment]
Thanks for reporting!
Would you mind opening an PR for both of your issues?

**Comment by mammuth** [comment]
Thanks for digging into the issue, @PetePete!

**Comment by PetePete** [comment]
> Thanks for reporting!
> Would you mind opening an PR for both of your issues?

Hi Aaron

Yes I will - I haven't set up an IDE or GIT for this yet - as soon as possible.

**Comment by mammuth** [comment]
Closed by #81
