### ISSUE TITLE
Use automatic Discovery of fritzbox as in fritzbox component

### ISSUE THREAD

**Issue by AaronDavidSchneider** [mammuth/ha-fritzbox-tools#86]
See https://github.com/home-assistant/core/blob/dev/homeassistant/components/fritzbox/config_flow.py

**Comment by jankatins** [comment]
This might depend on some other place to get activated, at least I copied the above to a custom component and it didn't automatically show up.

https://github.com/home-assistant/core/blob/dev/homeassistant/generated/ssdp.py#L20

**Comment by AaronDavidSchneider** [comment]
> This might depend on some other place to get activated, at least I copied the above to a custom component and it didn't automatically show up.
> 
> https://github.com/home-assistant/core/blob/dev/homeassistant/generated/ssdp.py#L20

Thanks for the hint! Maybe this helps:
https://developers.home-assistant.io/docs/creating_integration_manifest/#ssdp
