### ISSUE TITLE
Enable/Disable Port forwardings

### ISSUE THREAD

**Issue by mammuth** [mammuth/ha-fritzbox-tools#9]
Evaluate whether that's possible.

Nice use-case: Enable port 80 port forwarding to allow the let's encrypt http challenge to pass.

**Comment by AaronDavidSchneider** [comment]
it seems to be possible. There is a nice Shell script, which does that using UPNP: https://www.pack-eis.de/index.php?p=fbtr64toolbox.
I am not sure if it is possible to implement this feature using fritzconnection.

**Comment by jo-me** [comment]
I've just tried the shell script and it does in fact work. I can activate & deactivate the specified port forwarding. 👍   True heroes these guys 😁

**Comment by mammuth** [comment]
I think it should be possible with `fritzconnection` as well after a first glimpse (I guess this would be preferable, then we can keep everything in python and don't need to maintain two different dependencies.
See:
```
>>> con.get_action_arguments(service_name='Layer3Forwarding:1', action_name='SetForwardingEntryEnable')

[('NewDestIPAddress', 'in', 'string'), ('NewDestSubnetMask', 'in', 'string'), ('NewSourceIPAddress', 'in', 'string'), ('NewSourceSubnetMask', 'in', 'string'), ('NewEnable', 'in', 'boolean')]
```

**Comment by mammuth** [comment]
Related issue on the old `fritzconnection` repo: https://bitbucket.org/kbr/fritzconnection/issues/23/feature-request-list-change-port

So at least there is no easy to use utility method for handling port forwardings, but probably it's possible with the underlying `fritzconnection.py`.

Looks like the service is `WANIPConn:1`, which has a couple of actions related to `PortMapping`s.

**Comment by jo-me** [comment]
Yeah I thought I'd test the script to confirm that this method actually
works - contrary to some other methods I tried.
By the way, I have a 7590 with Fritz os 7.12

Max Muth <notifications@github.com> schrieb am Fr., 20. Sep. 2019, 11:17:

**Comment by AaronDavidSchneider** [comment]
I am working on this right now. You can use the function call_action with kwargs like this:
```
connection.call_action("WANIPConn:1","AddPortMapping",NewRemoteHost=remote_host,NewExternalPort=ext_port,NewInternalPort=int_port, NewInternalClient=client, NewProtocol=prot,NewLeaseDuration=duration, NewPortMappingDescription=description)
```

viewing the opened ports works already for me. fritzconnection converts the xml output of the html request into a dictionary, like this:
```
{'NewRemoteHost': '0.0.0.0', 'NewExternalPort': 80, 'NewProtocol': 'TCP', 'NewInternalPort': 80, 'NewInternalClient': '192.168.178.3', 'NewEnabled': '1', 'NewPortMappingDescription': 'HTTP-Server', 'NewLeaseDuration': 0}
```

Once I got a working solution, I will try to implement a switch for that and create a pull request.

**Comment by mammuth** [comment]
Cool, I tried it with `"WANIPConn:1"` for some reason (which did not work). Your examples work perfectly fine on my device as well 👍 

> Once I got a working solution, I will try to implement a switch for that and create a pull request.

Awesome!

Do you plan on doing a single switch per port mapping? Sounds correct to me. 

Some random thoughts:
- We probably need to somehow use the `unique_id` property of `Entity`, eg. `'fritzbox_portforward_{description}_{id}'`
- The setup method could use `GetGenericPortMappingEntry` over eg. `range(0,30)` to get all configured port mappings and create switches from it (I guess that was your idea, too?)

**Comment by AaronDavidSchneider** [comment]
This is my code so far:
```
import fritzconnection as fc

c = fc.FritzConnection(...)

n_ports = c.call_action('WANIPConnection:1', 'GetPortMappingNumberOfEntries')["NewPortMappingNumberOfEntries"]
port_mapping = []
for i in range(n_ports):
    port_mapping.append(c.call_action("WANIPConnection:1", "GetGenericPortMappingEntry",NewPortMappingIndex=i)) 

port_mapping[4]["NewEnabled"]= "0"
c.call_action("WANIPConnection:1","AddPortMapping",**port_mapping[4])
```

This works, BUT only if my ip is the ip of the port mapping I want to change. This has already been pointed out (https://www.ip-phone-forum.de/threads/tr-064-addportmapping-fritz-box-7490-113-07-01.302869/):
"Port mapping entries are only allowed for hosts inside of LAN. Furthermore hosts can only add port mapping entries for themselves and not for other hosts in the LAN. It is not intended to allow port mapping entries for the guest network or hosts with IP adresses routed into WAN."

Is there a variable in homeassistant that holds the ip ipadress? Or do we need to set this using extra packages like netifaces?

**Comment by jo-me** [comment]
> Is there a variable in homeassistant that holds the ip ipadress? Or do we need to set this using extra packages like netifaces?

Could this IP be retrieved from the fritzbox? maybe there is a request that mirrors the requesting IP?
 
Depending on the HA deployment (docker / venv / ..) it might be difficult to find a generic way that always works. Here's one way I found on the forums: https://community.home-assistant.io/t/show-ip-address-rpi/129607/2?u=jo-me

**Comment by AaronDavidSchneider** [comment]
Thankyou, I will have a look into that!
@jo-me: Did you manage to enable, disable ipv6 open ports with the script? Because my code only disables and enables ipv4 ports.

**Comment by AaronDavidSchneider** [comment]
Hey check out my pull request (see #12 ). I implemented the switch and it works for me.
At the moment it is necessary to configure the `ip_device` (ip of homeassistant) manually in configuration.yaml.
Would be nice if there were a different solution
