### ISSUE TITLE
Configuration problem for devices?

### ISSUE THREAD

**Issue by carsten-h** [mammuth/ha-fritzbox-tools#91]
Hello!

Inside the documentation I found this:

> As Integration (recommended):
>
> Go to the Integrations pane on your Home Assistant instance.

I installed the Tools there. But how can I now add the devices where the profiles should be switchable. I don't see anything where I can do this.

**Comment by mammuth** [comment]
During the set-up of the integration you can enter a comma-separated list of device names. For each of those devices a switch entity will be created that you can add to your Lovelace views.

So try removing the integration and then follow the set-up.

Feel free to re-open the issue if this didn't answer your question.

**Comment by carsten-h** [comment]
Yes, this answered my question! Thank you!
It seems I was to fast at clicking to see this.

Now I changed it and added all the devices I want to control. It seems only those that are online at the moment are created as entities.
How can I add more afterwards? Is it only possible with removing and adding the integration?

**Comment by mammuth** [comment]
> How can I add more afterwards

Did they automatically appear once they had been online once? If not, we're probably currently only supporting devices switches for devices that are online when the integration is installed.

**Comment by carsten-h** [comment]
No, I did not see any of them appearing. But there are a few devices which have double names is written inside the log. These are the DECT actors and some IP-devices which have the same name. Maybe this is a problem. I will try to change the names in a better way.
