### ISSUE TITLE
Disable Uptime Attribute

### ISSUE THREAD

**Issue by N1c093** [mammuth/ha-fritzbox-tools#93]
Hello,

first of all, thank you for this great integration.

Would it be possible to (optionally) disable the uptime attribute of the "binary_sensor.fritzbox_connectivity"
The binary sensor generates a lot of rows in the "home-assistant_v2.db" Database. It seems like, that the only reason is the changing uptime attribute.

Thanks in advance

**Comment by mammuth** [comment]
Good point. Maybe we could change it to the date of the last boot. This way the uptime could be calculated but we don't need to store each update.

**Comment by N1c093** [comment]
This sounds like a good solution :)

**Comment by N1c093** [comment]
I just had a look at fritzconnection. There is no attribute for the timestamp of last reconnect and it seems like, that it won't be implemented. https://github.com/kbr/fritzconnection/pull/47

Does it makes sense to calculate the timestamp inside the binary sensor?

Maybe we could do something like this. We just have to replace the "UPTIME" with the uptime attribute. 

```python

timestamp_lastreconnect = datetime.datetime.now() - datetime.timedelta(seconds="UPTIME")
return timestamp_lastreconnect.strftime("%Y-%m-%d %H:%M")

```

I just don't know how to implement this into the binary sensor.
Maybe you also know a better solution for it.

**Comment by AaronDavidSchneider** [comment]
Closed by latest release.
