### ISSUE TITLE
Logo in 0.110 beta

### ISSUE THREAD

**Issue by sagitt** [mammuth/ha-fritzbox-tools#94]
Is not an issue, but it will be in the next release
logos are now for custom components too

![Schermata 2020-05-16 alle 17 37 31](https://user-images.githubusercontent.com/169086/82123956-8036f880-979c-11ea-8f54-d919874bfb28.png)

**Comment by mammuth** [comment]
Thanks. Feel free to contribute a PR.

**Comment by N1c093** [comment]
I created a PR for it: https://github.com/home-assistant/brands/pull/1686
I hope it's fine to reuse the icons of the official fritzbox integration.

**Comment by mammuth** [comment]
Cool, thanks @N1c093

**Comment by N1c093** [comment]
There were some problems with my first pull request. Somehow the file type were mixed up.
I had to create a new PR, hopefully it will be reviewed soon.

https://github.com/home-assistant/brands/pull/1697

**Comment by mammuth** [comment]
Thanks for your efforts!

**Comment by N1c093** [comment]
The icons are now visible in HA.
I think the issue can be closed now. 

![Screenshot_20200626_065833](https://user-images.githubusercontent.com/59510296/85822234-af1c9300-b77a-11ea-911b-bccbda265cee.jpg)
