### ISSUE TITLE
Split configuration lock up HA startup

### ISSUE THREAD

**Issue by chemelli74** [mammuth/ha-fritzbox-tools#99]
Using the component from configuration.yaml in split mode doesn't allow HA to start.
My config:

**configuration.yaml:**

`fritzbox_tools: !include split/fritzbox_tools.yaml
`

**fritzbox_tools.yaml:**

```
  host: !secret fritz_ip
  username: !secret fritz_user
  password: !secret fritz_pwd
  use_wifi: true
  use_port: true
```

Simone

**Comment by chemelli74** [comment]
As configuring via configuration.yaml is not recommended, I would say this issue can be closed.

Simone

**Comment by mammuth** [comment]
Maybe we should get rid of it if it's broken anyways.
